"""Multi-window fleet-state evolution for Paper 5.

The simulator takes a Window-1 EEHDA fleet (generated by paper4's
EEHDAFleetGenerator) and evolves it across W windows according to the
pre-registered policy in PAPER5_PROTOCOL.md.

Per-window evolution rules
--------------------------
1. **Score** with current state (caller responsibility).
2. **Select**: caller passes top-K (host, CVE) pairs to remediate.
3. **Remediate**: mark the pair patched; reduce host patch debt; recover
   telemetry freshness for acted hosts.
4. **Disclose**: append Poisson(NEW_CVE_RATE) new (host, CVE) rows drawn
   from the same EPSS / CVSS / KEV distributions used at W1.
5. **Update**: random-walk perturb EPSS scores for all surviving unpatched
   pairs; clip to [0, 1].
6. **Drift**: increase staleness for non-acted hosts.

The simulator is deterministic given the seed; all RNG draws use a per-window
sub-generator seeded by (seed, window_index) so windows are independently
reproducible.

This module deliberately does NOT depend on paper4 source at import time —
the caller wires together generator → window_sim → scorers. We re-use
paper4's distributions through `_resample_*` helpers below, which mirror
paper4/src/hygieneprio/generator.py so a reader does not need to navigate
across packages to audit the per-window EPSS/CVSS/KEV draws.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Pre-registered simulation constants (PAPER5_PROTOCOL.md §4)
# ---------------------------------------------------------------------------

PATCH_DEBT_REDUCTION = 0.15        # Δ_patch per remediated pair on a host (relative debt drop)
NEW_CVE_RATE_PER_WINDOW = 3.0      # λ for Poisson new-CVE arrivals per window
EPSS_RW_SIGMA = 0.02               # Gaussian random-walk std for per-CVE EPSS drift
TELEMETRY_STALENESS_DRIFT = 0.08   # additive freshness drift per window (non-acted hosts), in [0,1]
TELEMETRY_FRESHNESS_RECOVERY = 0.30  # additive freshness recovery on acted hosts, in [0,1]
KEV_PREVALENCE = 0.08              # match paper4 generator
KEV_DECAY_LAMBDA_DEFAULT = 0.05    # scorer KEV recency decay constant


# ---------------------------------------------------------------------------
# Distribution helpers (mirror paper4/src/hygieneprio/generator.py)
# ---------------------------------------------------------------------------

def _sample_epss(n: int, rng: np.random.Generator) -> np.ndarray:
    low_mask = rng.random(n) < 0.88
    scores = np.where(
        low_mask,
        rng.beta(0.5, 8.0, n),
        rng.beta(2.0, 4.0, n),
    )
    return np.clip(scores, 1e-4, 1.0)


def _sample_cvss(n: int, rng: np.random.Generator) -> np.ndarray:
    categories = rng.choice([0, 1, 2, 3], size=n, p=[0.20, 0.35, 0.35, 0.10])
    scores = np.where(categories == 0, rng.uniform(2.0, 4.0, n),
             np.where(categories == 1, rng.uniform(4.0, 7.0, n),
             np.where(categories == 2, rng.uniform(7.0, 9.0, n),
                                        rng.uniform(9.0, 10.0, n))))
    return np.round(scores, 1)


# ---------------------------------------------------------------------------
# Simulation state
# ---------------------------------------------------------------------------

@dataclass
class FleetState:
    """Mutable fleet-state container threaded across windows.

    Tables follow paper4's schema so paper4's HRS and scorer modules can
    consume the state without modification.
    """

    vulnerability_records: pd.DataFrame  # (computer_id, cve_id, epss_score, cvss_base_score, in_kev, days_since_kev_entry, patch_lag_days, patched)
    computers: pd.DataFrame
    users: pd.DataFrame
    groups: pd.DataFrame
    group_membership_events: pd.DataFrame
    endpoint_patch_state: pd.DataFrame
    telemetry_freshness_log: pd.DataFrame

    def as_tables(self) -> dict[str, pd.DataFrame]:
        return {
            "computers": self.computers,
            "users": self.users,
            "groups": self.groups,
            "group_membership_events": self.group_membership_events,
            "vulnerability_records": self.vulnerability_records,
            "endpoint_patch_state": self.endpoint_patch_state,
            "telemetry_freshness_log": self.telemetry_freshness_log,
        }


# ---------------------------------------------------------------------------
# Window operations
# ---------------------------------------------------------------------------

def applicable_pairs(state: FleetState) -> pd.DataFrame:
    """Return only the unpatched (host, CVE) pairs — the live backlog."""
    vr = state.vulnerability_records
    return vr[~vr["patched"]].reset_index(drop=True)


def _recompute_patch_state(vr: pd.DataFrame) -> pd.DataFrame:
    summary = (
        vr.groupby("computer_id")
          .agg(total_cves=("cve_id", "count"),
               patched_count=("patched", "sum"))
          .reset_index()
    )
    summary["unpatched_count"] = summary["total_cves"] - summary["patched_count"]
    summary["patch_compliance_pct"] = (
        summary["patched_count"] / summary["total_cves"] * 100
    ).round(1)
    return summary


def apply_remediation(
    state: FleetState,
    selected_pairs: pd.DataFrame,
    *,
    host_col: str = "computer_id",
    cve_col: str = "cve_id",
) -> set[str]:
    """Mark the given pairs as patched. Return the set of acted host IDs.

    Patch-debt reduction is realised implicitly: marking a pair `patched=True`
    drops the host's unpatched count, lowering PatchPosture at the next HRS
    recomputation. The protocol's "−15% debt" parameter is the *expected*
    debt drop when ~15% of pairs are touched per window; we faithfully model
    it as one-pair-at-a-time rather than a multiplicative shrinkage.
    """
    vr = state.vulnerability_records
    key = list(zip(selected_pairs[host_col], selected_pairs[cve_col]))
    key_set = set(key)
    idx = vr.apply(lambda r: (r[host_col], r[cve_col]) in key_set, axis=1)
    state.vulnerability_records.loc[idx, "patched"] = True

    state.endpoint_patch_state = _recompute_patch_state(state.vulnerability_records)
    return set(selected_pairs[host_col].unique())


def disclose_new_cves(
    state: FleetState,
    rng: np.random.Generator,
    window_index: int,
    *,
    rate: float = NEW_CVE_RATE_PER_WINDOW,
) -> None:
    """Append Poisson(rate) new (host, CVE) rows.

    Each new CVE attaches to a random host drawn uniformly from the fleet,
    matching the per-host applicable-CVE accrual modelled by paper4.
    """
    n_new = int(rng.poisson(rate))
    if n_new == 0:
        return

    host_ids = state.computers["computer_id"].sample(
        n=n_new, replace=True, random_state=rng.integers(0, 2**31 - 1)
    ).values

    epss = _sample_epss(n_new, rng)
    cvss = _sample_cvss(n_new, rng)
    kev_flags = rng.random(n_new) < KEV_PREVALENCE
    kev_days = np.where(kev_flags, rng.integers(0, 30, size=n_new).astype(float), np.nan)

    # Synthesise stable, collision-free CVE IDs scoped to the disclosure window.
    base = state.vulnerability_records["cve_id"].nunique() + 1
    cve_ids = [f"CVE-W{window_index:02d}-{base + i:06d}" for i in range(n_new)]

    new_rows = pd.DataFrame({
        "computer_id": host_ids,
        "cve_id": cve_ids,
        "epss_score": np.round(epss, 4),
        "cvss_base_score": cvss.astype(float),
        "in_kev": kev_flags,
        "days_since_kev_entry": kev_days,
        "patch_lag_days": np.nan,  # not used downstream; introduced post-W1
        "patched": False,
    })
    state.vulnerability_records = pd.concat(
        [state.vulnerability_records, new_rows], ignore_index=True
    )
    state.endpoint_patch_state = _recompute_patch_state(state.vulnerability_records)


def update_epss(state: FleetState, rng: np.random.Generator) -> None:
    """Random-walk perturb EPSS scores for all surviving unpatched pairs."""
    mask = ~state.vulnerability_records["patched"]
    n = int(mask.sum())
    if n == 0:
        return
    noise = rng.normal(0.0, EPSS_RW_SIGMA, n)
    new_scores = state.vulnerability_records.loc[mask, "epss_score"].values + noise
    state.vulnerability_records.loc[mask, "epss_score"] = np.clip(new_scores, 1e-4, 1.0)


def update_telemetry_freshness(
    state: FleetState,
    acted_hosts: set[str],
) -> None:
    """Hosts acted on this window recover; non-acted hosts drift staler.

    The telemetry_freshness_log stores days_since_last_checkin in days, while
    HRS normalises by cap=30 to a [0,1] freshness score. We operate in the
    days domain so the recovered/drift quantities translate naturally:
      drift +0.08/window  ↔  +2.4 days/window
      recovery −0.30      ↔  reset toward 0 with floor at 0
    """
    log = state.telemetry_freshness_log.copy()
    drift_days = TELEMETRY_STALENESS_DRIFT * 30.0
    recovery_days = TELEMETRY_FRESHNESS_RECOVERY * 30.0

    acted_mask = log["computer_id"].isin(acted_hosts)
    log.loc[acted_mask, "days_since_last_checkin"] = np.maximum(
        0.0,
        log.loc[acted_mask, "days_since_last_checkin"] - recovery_days,
    )
    log.loc[~acted_mask, "days_since_last_checkin"] = (
        log.loc[~acted_mask, "days_since_last_checkin"] + drift_days
    ).clip(upper=60.0)
    state.telemetry_freshness_log = log


def advance_window(
    state: FleetState,
    selected_pairs: pd.DataFrame,
    window_index: int,
    seed: int,
) -> FleetState:
    """Apply one full window of evolution to ``state``.

    Steps (in order):
      1. Apply remediation for ``selected_pairs``.
      2. Disclose new CVEs.
      3. Random-walk EPSS.
      4. Update telemetry freshness (recover acted, drift non-acted).

    Each sub-step uses an RNG seeded by (seed, window_index, step_id) so the
    evolution is fully reproducible from the top-level seed.
    """
    rng = np.random.default_rng((seed, window_index, 0))

    acted_hosts = apply_remediation(state, selected_pairs)
    disclose_new_cves(state, rng, window_index)
    update_epss(state, rng)
    update_telemetry_freshness(state, acted_hosts)
    return state
